Add `wait_for_component()` (#63)
* add wait_for_component()

* revert #62

* testing if this fixes ImportError

* this should do it

* polishing it all up

* tweaked docstring and code

* Revert "revert #62"

This reverts commit a708e16de11f177edad6f38bb38a7b126a7873ab.

* used to_snowflake_list() and removed get_messages_ids()

* fixes TypeError: 'Message' object is not iterable

* fixes AttributeError: 'ComponentContext' object has no attribute 'origin_message_id'

* should fix not iterable error

* debugging

* more debugging

* removed debugging prints because IT WORKED LETS GOO

* fix typehint