Remove self from unicode reaction add
```
Traceback (most recent call last):
  File "E:\popularity-contest\env\lib\site-packages\dis_snek\client.py", line 326, in _async_wrap
    await _coro(_event, *_args, **_kwargs)
  File "E:\popularity-contest\env\lib\site-packages\dis_snek\models\listener.py", line 13, in __call__
    return await self.callback(*args, **kwargs)
  File "E:\popularity-contest\env\lib\site-packages\dis_snek\event_processors\reaction_events.py", line 24, in _on_raw_message_reaction_add
    emoji = Emoji.from_dict(event.data.get("emoji"), self)  # type: ignore
TypeError: DictSerializationMixin.from_dict() takes 2 positional arguments but 3 were given
```
` Emoji.from_dict()` doesn't need/use client.